name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
      - 'hotfix-*'

permissions:
  contents: read

jobs:
  build73:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
      - name: Install
        run: composer update
      - name: Test
        run: composer test
  build74:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install
        run: composer update
      - name: Test
        run: composer test
  build80:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install
        run: composer update
      - name: Test
        run: composer test
