name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
      - 'hotfix-*'

jobs:
  build71:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: shivammathur/setup-php@2.23.0
        with:
          php-version: '7.1.3'
      - name: Install
        run: composer update
      - name: Test
        run: composer test-legacy
  build72:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: shivammathur/setup-php@2.23.0
        with:
          php-version: '7.2'
      - name: Install
        run: composer update
      - name: Test
        run: composer test-legacy
  build73:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: shivammathur/setup-php@2.23.0
        with:
          php-version: '7.3'
      - name: Install
        run: composer update
      - name: Test
        run: composer test
  build74:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: shivammathur/setup-php@2.23.0
        with:
          php-version: '7.4'
      - name: Install
        run: composer update
      - name: Test
        run: composer test
  build80:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: shivammathur/setup-php@2.23.0
        with:
          php-version: '8.0'
      - name: Install
        run: composer update
      - name: Test
        run: composer test
